# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech-recognition-open-api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech-recognition-open-api.proto',
  package='speech_recognition',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!speech-recognition-open-api.proto\x12\x12speech_recognition\"b\n\x10RecognitionInput\x12\x16\n\taudio_url\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x61udio_bytes\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x42\x0c\n\n_audio_urlB\x0e\n\x0c_audio_bytes\"#\n\x11RecognitionOutput\x12\x0e\n\x06result\x18\x01 \x01(\t2n\n\x10SpeechRecognizer\x12Z\n\trecognize\x12$.speech_recognition.RecognitionInput\x1a%.speech_recognition.RecognitionOutput\"\x00\x62\x06proto3'
)




_RECOGNITIONINPUT = _descriptor.Descriptor(
  name='RecognitionInput',
  full_name='speech_recognition.RecognitionInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio_url', full_name='speech_recognition.RecognitionInput.audio_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='audio_bytes', full_name='speech_recognition.RecognitionInput.audio_bytes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_audio_url', full_name='speech_recognition.RecognitionInput._audio_url',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_audio_bytes', full_name='speech_recognition.RecognitionInput._audio_bytes',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=57,
  serialized_end=155,
)


_RECOGNITIONOUTPUT = _descriptor.Descriptor(
  name='RecognitionOutput',
  full_name='speech_recognition.RecognitionOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='speech_recognition.RecognitionOutput.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=192,
)

_RECOGNITIONINPUT.oneofs_by_name['_audio_url'].fields.append(
  _RECOGNITIONINPUT.fields_by_name['audio_url'])
_RECOGNITIONINPUT.fields_by_name['audio_url'].containing_oneof = _RECOGNITIONINPUT.oneofs_by_name['_audio_url']
_RECOGNITIONINPUT.oneofs_by_name['_audio_bytes'].fields.append(
  _RECOGNITIONINPUT.fields_by_name['audio_bytes'])
_RECOGNITIONINPUT.fields_by_name['audio_bytes'].containing_oneof = _RECOGNITIONINPUT.oneofs_by_name['_audio_bytes']
DESCRIPTOR.message_types_by_name['RecognitionInput'] = _RECOGNITIONINPUT
DESCRIPTOR.message_types_by_name['RecognitionOutput'] = _RECOGNITIONOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognitionInput = _reflection.GeneratedProtocolMessageType('RecognitionInput', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONINPUT,
  '__module__' : 'speech_recognition_open_api_pb2'
  # @@protoc_insertion_point(class_scope:speech_recognition.RecognitionInput)
  })
_sym_db.RegisterMessage(RecognitionInput)

RecognitionOutput = _reflection.GeneratedProtocolMessageType('RecognitionOutput', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONOUTPUT,
  '__module__' : 'speech_recognition_open_api_pb2'
  # @@protoc_insertion_point(class_scope:speech_recognition.RecognitionOutput)
  })
_sym_db.RegisterMessage(RecognitionOutput)



_SPEECHRECOGNIZER = _descriptor.ServiceDescriptor(
  name='SpeechRecognizer',
  full_name='speech_recognition.SpeechRecognizer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=194,
  serialized_end=304,
  methods=[
  _descriptor.MethodDescriptor(
    name='recognize',
    full_name='speech_recognition.SpeechRecognizer.recognize',
    index=0,
    containing_service=None,
    input_type=_RECOGNITIONINPUT,
    output_type=_RECOGNITIONOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHRECOGNIZER)

DESCRIPTOR.services_by_name['SpeechRecognizer'] = _SPEECHRECOGNIZER

# @@protoc_insertion_point(module_scope)
